namespace _37_ContentPresenterFallback
{
    [bindable]
    [default_interface]
    runtimeclass MyControl : Microsoft.UI.Xaml.Controls.ContentControl
    {
        MyControl();
        Object AnotherContent{ get; };
		static Microsoft.UI.Xaml.DependencyProperty AnotherContentProperty{ get; };
    }
}
